project_final/app/urls.py
from django.urls import path,include

from app.views import *

urlpatterns = [
    path('',home, name='home'),
    path('create/',create,name='create'),
    path('managefood/',managefood,name='managefood'),
    path('managefood/<str:date>/',managefood,name='managefood_add'),
    path('select_date/',select_date,name='select_date'),
    path('history_sale/',select_date,name='select_date'),
    path('clear_food/',clearfood,name='clear_food'),
    path('updatefood/<int:id>/',updatefood,name='updatefood'),
    path('search/',search,name='search'),
    path('review/<int:id>/',reviewfood,name='review'),
    path('admin1/', admin1, name='admin1'),
    path('management/', admin1, name='management'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('me/', Me, name='me'),
    path('signout', signout, name='signout'),
    path('registerXlogin', registerXlogin, name='registerXlogin'),
    path('register', register, name='register'),
    path('login', login, name='login'),
    path('payment/', payment, name='payment'),
    path('user_management/', user_management_view, name='user_management'),
    path('upload_profile_image/', upload_profile_image, name='upload_profile_image'),path('add_product/', add_product, name='add_product'),
    path('delete_product/<int:product_id>/', delete_product, name='delete_product'),
    path('add_cart/<int:id>/', add_cart, name='add_cart'),
    path('cart/',cart,name='cart'),
    path('order',order,name='order'),
    path('order2',order2,name='order2'),
    path('order3',order3,name='order3'),
    path('order4',order4,name='order4'),
    path('order5',order5,name='order5'),
    path('order6',order6,name='order6'),
    path('preorder/', preorder, name='preorder'),
    path('orders/', order, name='admin_order_list'),
    path('orders/', order, name='admin_order_list'),
    path('orders/update/<int:order_id>/', order, name='update_order_status'),
    path('orders/view/<int:order_id>/', order, name='view_order'),
    path('orders/track/<int:order_id>/', order, name='track_order'),
] 

project_final/project_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('app.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_final/app/models.py
from datetime import date, datetime
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='images_profile', null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    pass1 = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return self.user.username
# Create your models here.
#class Member(models.Model):
class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email =models.EmailField(blank=True,null=True)
    phone_number = models.CharField(max_length=100)
    pass1 = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=20, choices=(
        ('Male', 'ผู้ชาย'),
        ('Female', 'ผู้หญิง'),
        ('Other', 'อื่นๆ'),

    ), default='11-20') 
    def __str__(self) -> str:
        return f'{self.user_name} '


class Food(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    unit = models.CharField(max_length=100,default='บาทต่อถุง')
    score = models.FloatField(default=0,blank=True,null=True)
    quantity_review = models.IntegerField(default=0,blank=True,null=True)
    image = models.ImageField(upload_to='media/image/',blank=True,null=True)
    options = models.CharField(max_length=20, choices=(
        ('notchoose', 'ไม่ได้เลือก'),
        ('onsale', 'วางขาย'),
        ('soldout', 'ขายหมดแล้ว'),
    ), default='notchoose') 


    def __str__(self) -> str:
        return f'เมนู {self.name} ราคา {self.price} บาท status : {self.options}'
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height >300 or img.width >300:
                output_size = (300,300)
                img.thumbnail(output_size)
                img.save(self.image.path)
            
        
    
class Historysale(models.Model):
    date_field = models.DateField()
    food = models.ForeignKey(Food,on_delete=models.DO_NOTHING,null=True,blank=True)

    def __str__(self) -> str:
        return f'{self.date_field} {self.food}'
    
class Reviewfood(models.Model):
    food = models.ForeignKey(Food,on_delete=models.CASCADE)
    owner = models.ForeignKey(Member,on_delete=models.CASCADE,null=True)
    review = models.TextField(max_length=500,blank=True,null=True)
    created = models.DateTimeField(default=timezone.now)
    rating = models.IntegerField(choices=(
        (1, '1 ดาว'),
        (2, '2 ดาว'),
        (3, '3 ดาว'),
        (4, '4 ดาว'),
        (5, '5 ดาว'),

    ), default=5) 

    def __str__(self) -> str:
        return f'{self.food.name} rating : {self.rating}'
    

class Cart(models.Model):
    cart = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Detailcart(models.Model):
    itemImages = models.ImageField(upload_to='media/image/',blank=True,null=True)
    carts = models.ForeignKey(Cart, on_delete=models.CASCADE)
    amount = models.IntegerField()

class Order(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=2, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4')])
    material = models.CharField(max_length=50, choices=[('Vinyl', 'ป้ายไวนิลธงญี่ปุ่น'), ('Acrylic', 'ป้ายไวนิลโครงไม้/โครงเหล็ก'), ('Metal', 'ป้ายกล่องไฟไวนิล'), ('Wood', 'สติกเกอร์อิงค์เจ็ท'), ('Foamboard', 'แคนวาสอิงค์เจ็ท')])
    message = models.TextField()
    attachment = models.FileField(upload_to='order_attachments', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('จัดส่งแล้ว', 'จัดส่งแล้ว'), ('จัดส่งเรียบร้อย', 'จัดส่งเรียบร้อย')])


    def __str__(self):
        return f"Order {self.id}: {self.name} ({self.get_status_display()})"

project_final/app/templates/productweb/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
    <div class="container">
        {% block content %}
            <h2>Add Product</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{f.image.url}}
                <button type="submit">Add Product</button>
            </form>
        {% endblock %}
    </div>
</body>
</html>

project_final/app/templates/productweb/cart.html
{% load static %}
{% include 'base/tab_login.html' %}
{% include 'base/site_header.html' %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ตะกร้าสินค้า</title>
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
</head>
<div class="cart-container">
    <script src="{% static 'js/cart1.js' %}"></script>
    <h2>ตะกร้าสินค้า</h2>
    <table class="cart-table">
        <thead>
            <tr>
                <th>สินค้า</th>
                <th>ราคา</th>
                <th>จำนวน</th>
                <th>เลือกที่จะสั่ง</th>
                <th>การจัดการ</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            <tr>
                <td><input type="checkbox" name="selected_item" value="#" onclick="limitCheckboxSelection(this)"></td>
                <td>
                    <form action="{% url 'delete_product' item.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit">ลบรายการ</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="cart-total">
        <a id="checkout-link" href="{% url 'order' %}" onclick="return limitCheckboxSelectionAndSubmit();"><button id="checkout-btn">สั่งซื้อ</button></a>
    </div>
    <script>
        function limitCheckboxSelectionAndSubmit() {
            var selectedItems = document.querySelectorAll('input[name="selected_item"]:checked');
    
            if (selectedItems.length === 1) {
                var selectedProductName = selectedItems[0].parentNode.parentNode.cells[0].innerText.trim();
                if (selectedProductName === "ป้ายกล่องไฟ") {
                    window.location.href = "{% url 'order2' %}";
                } else if (selectedProductName === "ป้ายสติ๊กเกอร์") {
                    window.location.href = "{% url 'order3' %}";
                } else if (selectedProductName === "ป้ายรีดฟิวเจอร์บอร์ด") {
                    window.location.href = "{% url 'order4' %}";
                } else if (selectedProductName === "ป้ายอักษรพลาสวูด") {
                    window.location.href = "{% url 'order5' %}";
                } else if (selectedProductName === "ป้ายรีดโฟมบอร์ด") {
                    window.location.href = "{% url 'order6' %}";
                } else {
                    window.location.href = "{% url 'order' %}";
                }
            } else {
                alert("Please select only one item to proceed with the order.");
            }
            return false; // Prevent default link action
        }
    </script>
</div>

project_final/app/templates/productweb/contag.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>contag</title>
  <link rel="stylesheet" href="{% static 'css/contag1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
  <div class="container">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3862.8808659807587!2d105.01252527585248!3d14.491527785981965!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3111559c1f15bdfd%3A0x5d1486ec4655e8b6!2z4LiZ4LmJ4Liz4Lii4Li34LiZ4LiB4Lij4Liy4Lif4Lif4Li04LiE!5e0!3m2!1sth!2sth!4v1707293881535!5m2!1sth!2sth" width="1000" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    <div class="contact-info">
      <p><strong>Line ID:</strong> <span class="line-id">@wasdwadsawds</span></p>
      <p><strong>โทรศัพท์:</strong> <span class="phone-number">0981234567</span></p>
      <p><strong>ชื่อร้าน:</strong> ร้านบุญตา</p>
      <p><strong>Email:</strong> <a href="mailto:wasd@gmail.com" class="email">wasd@gmail.com</a></p>
    </div>
  </div>

</body>

</html>

project_final/app/templates/productweb/delete_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Product</title>
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
    <div class="container">
        {% block content %}
            <h2>Delete Product</h2>
                <p>แน่ใจไหมว่าจะลบสินค้า '{{ product.title }}'?</p>
                <p class="product-size">ขนาด : {{ product.size }}</p>
                <p class="product-matter">{{ product.matter }}</p>
                <p class="product-description">{{ product.description }}</p>
                <p class="product-price">{{product.price}}</p>
            <form method="post" id="delete-form">
                {% csrf_token %}
                <button type="submit">Delete</button>
                <a href="{% url 'products' %}" class="cancel-link">Cancel</a>
            </form>
        {% endblock %}
    </div>
</body>
</html>

project_final/app/templates/productweb/order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
<div class="container">
  <h2>ข้อมูลป้ายไวนิลที่จะสั่งทำ</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <label for="name">ชื่อป้ายที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="ชื่อป้าย" required>

    <label for="category">รายการอาหาร</label>
    <select id="category" name="category">
      <option value="A0">1</option>
      <option value="A1">2</option>
      <option value="A2">3</option>
      <option value="A3">4</option>
      <option value="A4">5</option>      
    </select>
    

    <label for="material">เมนู:</label>
    <select id="material" name="material">
      <option value="Vinyl">1</option>
      <option value="Acrylic">2</option>
      <option value="Metal">3</option>
      <option value="Wood">4</option>
      <option value="Foamboard">5</option>
    </select>    

    <label for="message">เมนูเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="เพิ่มเติมเกี่ยวกับเมนู"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>
<script src="{% static 'js/order1.js' %}"></script>
</body>
</html>

project_final/app/templates/productweb/order2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายที่จะสั่งทำป้ายไฟ</h2>
  <form>
    <label for="name">ชื่อป้ายที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="Your name">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="General">15 x 40 ซม.</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="category">วัสดุป้าย:</label>
    <select id="category" name="category">
      <option value="General">General</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

project_final/app/templates/productweb/order3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายสติ๊กเกอร์ที่จะสั่งทำ</h2>
  <form>
    <label for="name">ชื่อป้ายที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="Your name">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="General">15 x 40 ซม.</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="category">วัสดุป้าย:</label>
    <select id="category" name="category">
      <option value="General">General</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

project_final/app/templates/productweb/order4.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายรีดฟิวเจอร์บอร์ดที่จะสั่งทำ</h2>
  <form>
    <label for="name">ชื่อป้ายที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="Your name">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="General">15 x 40 ซม.</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="category">วัสดุป้าย:</label>
    <select id="category" name="category">
      <option value="General">General</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

project_final/app/templates/productweb/order5.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายอักษรพลาสวูดที่จะสั่งทำ</h2>
  <form>
    <label for="name">ชื่อป้ายที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="Your name">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="General">15 x 40 ซม.</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="category">วัสดุป้าย:</label>
    <select id="category" name="category">
      <option value="General">General</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

project_final/app/templates/productweb/order6.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>สั่งซื้อป้าย</title>
<link rel="stylesheet" href="{% static 'css/order1.css' %}">
</head>
<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
<div class="container">
  
  <h2>ข้อมูลป้ายรีดโฟมบอร์ดที่จะสั่งทำ</h2>
  <form>
    <label for="name">ชื่อป้ายที่ต้องการ:</label>
    <input type="text" id="name" name="name" placeholder="Your name">

    <label for="category">ขนาดป้าย:</label>
    <select id="category" name="category">
      <option value="General">15 x 40 ซม.</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="category">วัสดุป้าย:</label>
    <select id="category" name="category">
      <option value="General">General</option>
      <option value="Inquiry">Inquiry</option>
      <option value="Feedback">Feedback</option>
    </select>

    <label for="message">รายละเอียดป้ายเพิ่มเติม:</label>
    <textarea id="message" name="message" placeholder="Your message"></textarea>

    <label for="attachment">Attachment:</label>
    <input type="file" id="attachment" name="attachment">

    <button type="submit">Order</button>
    
  </form>
</div>

</body>
</html>

project_final/app/templates/productweb/preorder.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/preorder1.css' %}">
<title>รายการสั่งซื้อ</title>
</head>

<body>
  {% include 'base/tab_login.html' %}
  {% include 'base/site_header.html' %}
  <div class="container">
    <h1>รายการ Order</h1>
    <div class="order-box">
      <div class="order-details">
        <div>
          <label>เลขคำสั่งซื้อ:</label> <a href="#">{{ order.id }}</a>
        </div>
        <div>
          <label>เวลาสั่งซื้อ:</label> {{ order.created_at }}
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>ชื่อผู้สั่ง:</label> {{ order.user_profile.first_name }} {{ order.user_profile.last_name }}
        </div>
        <div>
          <label>สถานะ:</label> {{ order.get_status_display }}
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>ชื่อป้าย:</label> {{ order.name }}
        </div>
        <div>
          <label>ขนาด:</label> {{ order.get_category_display }}
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>แบบป้าย:</label> {{ order.get_material_display }}
        </div>
        <div>
          <label>รายละเอียดเพิ่มเติม:</label> {{ order.message }}
        </div>
      </div>
      <div class="order-details">
        <div>
          <label>ไฟล์งานเพิ่มเติม:</label>
          {% if order.attachment %}
          <a href="{{ order.attachment.url }}">ดาวน์โหลด</a>
          {% else %}
          N/A
          {% endif %}
        </div>
        <div>
          <a class="status-button" href="#">ดูสถานะ</a>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

project_final/app/templates/productweb/product_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ item.title }} Detail</title>
    <link rel="stylesheet" href="{% static 'css/product_detail3.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
  <br>
  <div class="product-detail-container">
    <div class="image-slider">
      <div class=".product-image" >
      {% for image in item.images.all %}
        <img class="product-image{% if forloop.first %} active{% endif %}" src="{{ image.image.url }}" alt="{{ item.title }} Image" >
      {% endfor %}
      <button class="prev" onclick="changeImage(-1)">&#10094;</button>
      <button class="next" onclick="changeImage(1)">&#10095;</button>
    </div>
    <div class="product-info">
        <h2 class="product-title">{{ item.title }}</h2>
        <p class="product-size">{{ item.size }}</p>
        <p class="product-matter">{{ item.matter }}</p>
        <p class="product-description">{{ item.description }}</p>
        <p class="product-price">{{item.price}}</p>
        
        {% if user.is_authenticated %}
    {% if item.title == "ป้ายกล่องไฟ" %}
        <a id="checkout-link" href="{% url 'order2' %}"><button id="checkout-btn" onclick="orderProduct('{{ item.title }}')">สั่งซื้อ</button></a>
    {% elif item.title == "ป้ายสติ๊กเกอร์" %}
        <a id="checkout-link" href="{% url 'order3' %}"><button id="checkout-btn" onclick="orderProduct('{{ item.title }}')">สั่งซื้อ</button></a>
    {% elif item.title == "ป้ายรีดฟิวเจอร์บอร์ด" %}
        <a id="checkout-link" href="{% url 'order4' %}"><button id="checkout-btn" onclick="orderProduct('{{ item.title }}')">สั่งซื้อ</button></a>
    {% elif item.title == "ป้ายอักษรพลาสวูด" %}
        <a id="checkout-link" href="{% url 'order5' %}"><button id="checkout-btn" onclick="orderProduct('{{ item.title }}')">สั่งซื้อ</button></a>
    {% elif item.title == "ป้ายรีดโฟมบอร์ด" %}
        <a id="checkout-link" href="{% url 'order6' %}"><button id="checkout-btn" onclick="orderProduct('{{ item.title }}')">สั่งซื้อ</button></a>
    {% elif item.title == "ป้ายไวนิล" %}
        <a id="checkout-link" href="{% url 'order' %}"><button id="checkout-btn" onclick="orderProduct('{{ item.title }}')">สั่งซื้อ</button></a>
    {% else %}
        <a id="checkout-link" href="{% url 'order' %}"><button id="checkout-btn" onclick="orderProduct('{{ item.title }}')">สั่งซื้อ</button></a>
    {% endif %}
    {% else %}
    <button type="button" onclick="redirectToLogin()">สั่งซื้อ</button>
    {% endif %}
        <script src="{% static 'js/detail.js' %}"></script>
    </div>
</div>
</body>
</html>

project_final/app/templates/productweb/track_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ติดตามคำสั่งซื้อ</title>
<link rel="stylesheet" href="{% static 'css/track.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
    <div class="container">
        <h1>ติดตามคำสั่งซื้อ</h1>
        <p><strong>สถานะการทำงาน:</strong> {{ order_status }}</p>
        <p><strong>เลขคำสั่งซื้อ:</strong> {{ order.id }}</p>
        <a href="{% url 'view_order' order_id=order.id %}">ดูรายละเอียดคำสั่งซื้อ</a>
    </div>
</body>
</html>