project_final/app/urls.py
from django.urls import path,include

from app.views import *

urlpatterns = [
    path('',home, name='home'),
    path('create/',create,name='create'),
    path('managefood/',managefood,name='managefood'),
    path('managefood/<str:date>/',managefood,name='managefood_add'),
    path('select_date/',select_date,name='select_date'),
    path('history_sale/',select_date,name='select_date'),
    path('clear_food/',clearfood,name='clear_food'),
    path('updatefood/<int:id>/',updatefood,name='updatefood'),
    path('search/',search,name='search'),
    path('review/<int:id>/',reviewfood,name='review'),
    path('admin1/', admin1, name='admin1'),
    path('management/', admin1, name='management'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('me/', Me, name='me'),
    path('signout', signout, name='signout'),
    path('registerXlogin', registerXlogin, name='registerXlogin'),
    path('register', register, name='register'),
    path('login', login, name='login'),
    path('payment/', payment, name='payment'),
    path('user_management/', user_management_view, name='user_management'),
    path('upload_profile_image/', upload_profile_image, name='upload_profile_image'),path('add_product/', add_product, name='add_product'),
    path('delete_product/<int:product_id>/', delete_product, name='delete_product'),
    path('add_cart/<int:id>/', add_cart, name='add_cart'),
    path('cart/',cart,name='cart'),
    path('order',order,name='order'),
    path('order2',order2,name='order2'),
    path('order3',order3,name='order3'),
    path('order4',order4,name='order4'),
    path('order5',order5,name='order5'),
    path('order6',order6,name='order6'),
    path('preorder/', preorder, name='preorder'),
    path('orders/', order, name='admin_order_list'),
    path('orders/', order, name='admin_order_list'),
    path('orders/update/<int:order_id>/', order, name='update_order_status'),
    path('orders/view/<int:order_id>/', order, name='view_order'),
    path('orders/track/<int:order_id>/', order, name='track_order'),
] 

project_final/project_final/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('app.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_final/app/models.py
from datetime import date, datetime
from django.db import models
from PIL import Image
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='images_profile', null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    pass1 = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return self.user.username
# Create your models here.
#class Member(models.Model):
class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email =models.EmailField(blank=True,null=True)
    phone_number = models.CharField(max_length=100)
    pass1 = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=20, choices=(
        ('Male', 'ผู้ชาย'),
        ('Female', 'ผู้หญิง'),
        ('Other', 'อื่นๆ'),

    ), default='11-20') 
    def __str__(self) -> str:
        return f'{self.user_name} '


class Food(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    unit = models.CharField(max_length=100,default='บาทต่อถุง')
    score = models.FloatField(default=0,blank=True,null=True)
    quantity_review = models.IntegerField(default=0,blank=True,null=True)
    image = models.ImageField(upload_to='media/image/',blank=True,null=True)
    options = models.CharField(max_length=20, choices=(
        ('notchoose', 'ไม่ได้เลือก'),
        ('onsale', 'วางขาย'),
        ('soldout', 'ขายหมดแล้ว'),
    ), default='notchoose') 


    def __str__(self) -> str:
        return f'เมนู {self.name} ราคา {self.price} บาท status : {self.options}'
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)
            if img.height >300 or img.width >300:
                output_size = (300,300)
                img.thumbnail(output_size)
                img.save(self.image.path)
            
        
    
class Historysale(models.Model):
    date_field = models.DateField()
    food = models.ForeignKey(Food,on_delete=models.DO_NOTHING,null=True,blank=True)

    def __str__(self) -> str:
        return f'{self.date_field} {self.food}'
    
class Reviewfood(models.Model):
    food = models.ForeignKey(Food,on_delete=models.CASCADE)
    owner = models.ForeignKey(Member,on_delete=models.CASCADE,null=True)
    review = models.TextField(max_length=500,blank=True,null=True)
    created = models.DateTimeField(default=timezone.now)
    rating = models.IntegerField(choices=(
        (1, '1 ดาว'),
        (2, '2 ดาว'),
        (3, '3 ดาว'),
        (4, '4 ดาว'),
        (5, '5 ดาว'),

    ), default=5) 

    def __str__(self) -> str:
        return f'{self.food.name} rating : {self.rating}'
    

class Cart(models.Model):
    cart = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


class Detailcart(models.Model):
    itemImages = models.ImageField(upload_to='media/image/',blank=True,null=True)
    carts = models.ForeignKey(Cart, on_delete=models.CASCADE)
    amount = models.IntegerField()

class Order(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=2, choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4')])
    material = models.CharField(max_length=50, choices=[('Vinyl', 'ป้ายไวนิลธงญี่ปุ่น'), ('Acrylic', 'ป้ายไวนิลโครงไม้/โครงเหล็ก'), ('Metal', 'ป้ายกล่องไฟไวนิล'), ('Wood', 'สติกเกอร์อิงค์เจ็ท'), ('Foamboard', 'แคนวาสอิงค์เจ็ท')])
    message = models.TextField()
    attachment = models.FileField(upload_to='order_attachments', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('กำลังดำเนินการ', 'กำลังดำเนินการ'), ('จัดส่งแล้ว', 'จัดส่งแล้ว'), ('จัดส่งเรียบร้อย', 'จัดส่งเรียบร้อย')])


    def __str__(self):
        return f"Order {self.id}: {self.name} ({self.get_status_display()})"

project_final/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% block content %} 
    
    {% endblock %} 
</body>
</html>

project_final/app/templates/app/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create</title>
    <style>
        /* set container เพื่อให้ไปอยูาตรงกลาง สำหรับ form  */
        body {
            background-color: #ffffff;
        }
        .container  {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 70vh;
        }
         /* ตั้งค่า form (กล่องของ form ใหญ่) */
        .form-data {
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid  #ccc;
            padding: 20px;/*ขนาดของกลาง form-data ให้มรขนาดช่วงว่างเยอะขึ้น */
            border-radius: 10px; /*ทำให้มุมมนไม่เหลี่ยม */
            background-color: #ffffff;
        }
        .form-detail {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-between;
        }

        .form_data {
            flex: 1;
            margin-right: 20px;
        }

        .form_image {
            flex: 1;
        }

        .form_data div {
            margin-bottom: 10px;
        }

        /* Beautify form fields */
        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        input[type="file"] {
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
            width: calc(100% - 10px); /* Adjust the width to align properly */
            margin-bottom: 10px;
        }

        input[type="submit"] {
            padding: 8px 20px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            background-color: #3498db;
            color: #fff;
            width: 100%;
        }
    </style>
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
    <div class="container">
        <form action="/create/" method="post" enctype="multipart/form-data" class="form-data">
            {%csrf_token%}
            <div class="form-detail">
        
                <div class="form_data">
                    <div class="food_name">
                        <label for="id_name">name</label>
                        <input type="text" name="name" step="any" required id="id_name">
                    </div>
                    <div class="food_price">
                        <label for="id_price">price</label>
                        <input type="number" name="price" step="any" required id="id_price">
                    </div>
                    <div class="food_unit">
                        <label for="id_unit">หน่วยต่อถุง</label>
                        <input type="text" name="unit" step="any" required id="id_unit" value="บาทต่อถุง">
                    </div>
                </div>

            </div>
            
            <div class="form_image">
                <div class="upload_image">
                    <label for="id_image"></label>
                    <input type="file" name="image" required id="id_image">
                </div>
            </div>
            <input type="submit" value="submit">
            

        </form>
        
    </div>

</body>
</html>

project_final/app/templates/app/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>แก้ไขประวัติ</title>
    <link rel="stylesheet" href="https://cdn.tailwindcss.com">
</head>
<style>
    body {
  font-family: 'Arial', sans-serif;
  margin: 0;
  padding: auto;
  background-color: #f8f9fa;
  min-height: 100vh;
  justify-content: center;
  align-items: center;
}

.profile-container {
  max-width: 600px;
  background-color: #ffffff;
  box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
  padding: 20px;
  margin-top: 20px;
  text-align: left;
  margin: auto;
}

.profile-image {
  width: 150px;
  height: 150px;
  border-radius: 50%;
  object-fit: cover;
  margin-bottom: 20px;
}

.profile-name {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 10px;
  color: #007bff; /* Change color to a blue shade */
}

.profile-info {
  font-size: 16px;
  color: #868e96;
  margin-bottom: 20px;
}

form {
  margin-top: 20px;
}

button {
  background-color: #007bff;
  color: #fff;
  border: none;
  padding: 10px 20px;
  font-size: 16px;
  cursor: pointer;
  border-radius: 4px;
  transition: background-color 0.3s ease; /* Add transition for a smoother hover effect */
}

button:hover {
  background-color: #0056b3;
}

/* Add some spacing to the date of birth labels and select boxes */
form label,
form select {
  margin-bottom: 10px;
}

/* Style the text input fields */
form input {
  padding: 8px;
  width: 100%;
  box-sizing: border-box;
  margin-bottom: 10px;
}

/* Style the back-to-profile button */
a button {
  background-color: #6c757d; /* Gray color */
}

a button:hover {
  background-color: #495057; /* Darker gray color on hover */
}

/* Adjust styling for smaller screens */
@media (max-width: 768px) {
  .profile-container {
    padding: 15px;
  }
}

@keyframes move{
  0%, 49.99%{
      opacity: 0;
      z-index: 1;
  }
  50%, 100%{
      opacity: 1;
      z-index: 5;
  }
}

</style>
<body>
    {% include 'base/site_header.html' %}
    <br>
    {% block content %}
    <div class="profile-container">
    <form method="post" enctype="multipart/form-data" action="{% url 'edit_profile' %}">
        {% csrf_token %}
        <h1>แก้ไขประวัติ</h1>
        <p class="profile-info">ชื่อ : {{ form.first_name }}</p>
        <p class="profile-info">นามสกุล : {{ form.last_name }}</p>
        <p class="profile-info">email : {{ form.email }}</p>
        <p class="profile-info">เบอร์โทรศัพท์ : {{ form.phone_number }}</p>
        <p class="profile-info">ที่อยู่ : {{ form.address }}</p>     
        <label for="day">วัน:</label>
        <select id="day" name="day"></select>
        <label for="month">เดือน:</label>
        <select id="month" name="month"></select>
        <label for="year">ปี:</label>
        <select id="year" name="year"></select>
        <br>
        <br>
        <button type="submit">บันทึก</button> 
    </form>
    <br>
    <a href="{% url 'profile' %}"><button>กลับไปที่โปรไฟล์</button></a>
    <script src="{% static 'js/edit.js' %}"></script>
</div>
{% endblock %}

</body>
</html>

project_final/app/templates/app/historysales.html
<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ManageFood</title>
    <style>
        /* ส่วน bar จัดการเมนูอาหาร */
        .containerbody {
            display: flex;
            justify-content: start;
            border: 1px solid red;
            padding: 20px;
            margin-top: 50px;

        }
        .container {
            width: 700px;
            border: 1px solid #333;
            padding: 10px;
            margin-left: 20px;
            box-shadow: 5px 5px seashell;
        }
        .managebar {
            display: flex;
            justify-content: space-between;
            align-items: center;

        }

        a {
            list-style: none;
            text-decoration: none;
            color: black;
        }
        .choosedate {
            border: 1px solid #333;
            padding: 10px;

        }
        .addfood {
            border: 1px solid #333;
            padding: 10px;
            margin-right: 20px;
        }
        .clearfood {

            border: 1px solid #333;
            padding: 10px;

        }
        /* block ส่วน แสดงเมนูอาหาร */
        
        .container-area {
            display: grid;
            padding: 0.5rem;
            margin: 0.5rem;
            grid-template-columns: repeat(4,1fr);
            grid-gap: 10px;
            width: 1140px;
            border: 1px solid red;
            margin: 0 auto;
            margin-top: 20px;

        }
        .boxlistfood {
            border: 1px solid blue;
            height: auto;
            margin: 10px;

    
            
        }
        .boxlistfood div {
            margin-top: 5px;
            text-align: center;
  
            
        }

        .listitem a {
            text-decoration: none;
            color: black;


        }
        .image-food {
            width: 100% ;
            border: 1px solid blue;
            height: auto;
            margin-top: 0;

        }
        .image-food img {
            height: 120px; /* Set the height of the image container */
            width: 90%; /* Set the width of the image container */
            
        }
        .detail_food {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin: 10px;

        }

        .foodname {
            text-align: center;
        }
        .options_sale {
            display: flex;
            justify-content: flex-end;
            border: 1px solid #333;
        
        }


    </style>
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}

    <div class="containerbody">
        <div class="container">
            <div class="managebar">
                <!-- <a href="#" class="choosedate">เลือกวันที่</a> -->
                <form action="/select_date/" method="post">
                    {% csrf_token %}
                    <!-- Render DateField -->
                    <label for="id_my_date_field">เลือกวันที่</label>
                    {{ form.date_field }}
                    <button type="submit">Submit</button>
                </form>
                <div class="showdate">{{thai_date}}</div>
                <div class="rightbar">
                    <a href="/create/" class="addfood">เพิ่มเมนูอาหาร</a>
                    <a href="#" class="clearfood">จบวัน</a>
                </div>
            </div>
        </div>
    </div>
    <form class="submit_sales" method="post" action="/managefood/{{date}}/">
        {%csrf_token%}
        <div class="container-area">
            {%for f in food %}
                        <div class="boxlistfood">
                            {%if f.image %}
                            <div class="image-food">
                                <img src="{{f.image.url}}" alt="food-image">
                            </div>
                            {%endif%}
                            <div class="foodname">{{f.name}}</div> 

                            <div class="detail_food">
                                <div>{{f.price}} {{f.unit}}</div>
                                {%if f.score%}
                                    <div>{{f.score}}</div>
                                {%endif%}

                                {%if f.quantity_review >= 10%}
                                    <div>({{f.quantity_review}})</div>
                                {%endif%}
                            </div>
                        </div>   
            {%endfor%}
        </div>
        <button type="submit">OK</button>
        <button type="submit">cancel</button>
    </form>

</body>
</html>

project_final/app/templates/app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>โน้ตอาหารตามสั่ง</title>
</head>
<body>
    <aiv>
        {% include 'base/tab_login.html' %}
        {% include 'base/site_header.html' %}
        <br>
        {% include 'base/previews.html' %}
        
    </div>
</html>

project_final/app/templates/app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
    <div class="container">
        <h3>เข้าสู่ระบบ</h3>
        <form method="post" action="/login" class="mb-2">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter Your Username" required>
            </div>
            <div class="form-group">
                <label for="pass1">รหัสผ่าน</label>
                <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Enter Your Password" required>
            </div>

            <button type="submit" class="btn btn-primary">ล็อกอิน</button>
        </form>
    </div>
</body>
</html>

project_final/app/templates/app/me.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>การติดต่อ</title>
</head>

<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
        <div class="container">
            <iframe src="https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d1618.8202834193507!2d104.86802386858513!3d15.20083749816959!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zMTXCsDEyJzAyLjMiTiAxMDTCsDUyJzA1LjciRQ!5e0!3m2!1sth!2sth!4v1707883304038!5m2!1sth!2sth" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            <div class="contact-info">
              <p><strong>Line ID:</strong> <span class="line-id">@Note</span></p>
              <p><strong>โทรศัพท์:</strong> <span class="phone-number">000-000-0000</span></p>
              <p><strong>ชื่อร้าน:</strong> โน้ตอาหารตามสั่ง</p>
              <p><strong>Email:</strong> <a href="mailto:chatchai.so.64@ubu.ac.th" class="email">chatchai.so.64@ubu.ac.th</a></p>
            </div>
        </div>
</body>
</html>

project_final/app/templates/app/navbar.html
<style>
        body {
            margin: 0;
            padding: 0;
        }
        .navbar {
            display: flex;
            height: 70px;
            background-color: #c4bf8b;
           
            align-items: center;
  
        }
        ul {
            display: flex;
            list-style: none;
        }
        ul li {
            margin: 3 lr;
            
        }
        ul li a {
            color: rgb(255, 255, 255);
            text-decoration: none;

        }

        .logoitem {
            margin-left: 20px;
            display: flex;

        }
        .leftitem {
            display: flex;
            margin-right: 44%;
            align-items: center;
            justify-content: space-between;

            
        }
        .about-us {
            width: 90px;
            
        }
        .about-us a {
            display: inline;
            margin: 0;
            padding: 0;
            text-align: center;
            margin-left: 20px;
        }
        div li {
            list-style: none;
        }
        div li a {
            color: rgb(0, 0, 0);
            text-decoration: none; 
            margin-left:30px ;
        }

        .rightitem {
            margin-right: 10px;
        }
        div h1 a {
            color: rgb(0, 0, 0);
            text-decoration: none;
            list-style: none;
        }
        .searchbar {
            display: flex;
            align-items: center;
        }

        .search button {
            padding: 8px 20px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            background-color: #3498db;
            color: #fff;
            height: 23px; /* Adjusted height */
            margin-left: 5px; /* Added margin to separate input and button */
            font-size: small;
            line-height: 10px; /* Aligns text vertically within the button */
        }

        .leftitem form {
            display: flex;
            align-items: center;
        }

        
        .container {
             display: inline-block;
             cursor: pointer;
        }

        .bar1, .bar2, .bar3 {
            width: 35px;
            height: 5px;
            background-color: #333;
            margin: 6px 0;
            transition: 0.4s;
        }

        .change .bar1 {
            transform: translate(0, 11px) rotate(-45deg);
        }

        .change .bar2 {opacity: 0;}

        .change .bar3 {
            transform: translate(0, -11px) rotate(45deg);
        }

</style>
<header>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
    <nav class="navbar">
        <div class="logoitem">
            <h1 class="res_name"><a href="">โน้ตอาหารตามสั่ง</a></h1>
        </div>

        <div class="leftitem">
            <li class="about-us"><a href="#">ค้นหา</a></li>
            <form class="search" method="post" action="/search/">
                {%csrf_token%}
                <div class="searchbar">
                    <input type="search" aria-label="Search" name="text-search">
                    <button type="submit">Search</button>
                </div>
            </form>
        </div>
        <div class="h12">
            <h1 class=""><a href="login/">ตะกล้า</a></h1>
        </div>
      



        <div class="container" onclick="myFunction(this)">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>

        <script>
            function myFunction(x) {
            x.classList.toggle("change");
            }   
        </script>

        <div class="h6">
            <h1 class="login"><a href="login/">Login/sign up</a></h1>
        </div>
        <br>
        

        <div class="rightitem">
            <ul>
                {% if user.is_authenticated %}
                   <li class="orderfood"><a href="#">{{member.user_name}}</a></li>
                {%endif%}
            </ul>
        </div>
    </nav>
</header>

project_final/app/templates/app/payment.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>contag</title>
  <link rel="stylesheet" href="{% static 'css/pay.css' %}">
</head>

<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
  <div class="container">
    <div class="contact-info">
        <img src="https://th.bing.com/th/id/OIP.rdCAao4EKVgkFjc_UgvMrAHaHa?w=201&h=201&c=7&r=0&o=5&pid=1.7" alt="รูปภาพ">
      <p><strong>บัญชีธนาคาร:</strong> <span class="line-id">000-000-0000</span></p>
      <p><strong>หมายเหตุ:</strong> <span class="context">ราคาสินค้าท่านจะได้รับประมาณ10.00-11.30 โมง ของทุกวัน </span></p>

    </div>
  </div>

</body>

</html>

project_final/app/templates/app/updatefood.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create</title>
    <style>
        .main-container {
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-direction: row;
            margin: 20px;
            width: 1200px;
        }
        /* set container เพื่อให้ไปอยูาตรงกลาง สำหรับ form  */
        .container  {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 70vh;
            flex-direction: row;
            margin-left: 400px;
        }
         /* ตั้งค่า form (กล่องของ form ใหญ่) */
        .form-data {
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid  #ccc;
            padding: 20px;/*ขนาดของกลาง form-data ให้มรขนาดช่วงว่างเยอะขึ้น */
            border-radius: 10px; /*ทำให้มุมมนไม่เหลี่ยม */
            background-color: #f9f9f9;
        }
        .form-detail {
            display: flex;
            flex-wrap: wrap;
            width: 100%;
            justify-content: space-between;
        }

        .form_data {
            flex: 1;
            margin-right: 20px;
        }

        .form_image {
            flex: 1;
        }

        .form_data div {
            margin-bottom: 10px;
        }

        /* Beautify form fields */
        label {
            font-weight: bold;
            margin-bottom: 5px;
        }

        input[type="text"],
        input[type="number"],
        input[type="file"] {
            padding: 8px;
            border-radius: 4px;
            border: 1px solid #ccc;
            width: calc(100% - 10px); /* Adjust the width to align properly */
            margin-bottom: 10px;
        }

        input[type="submit"] {
            padding: 8px 20px;
            border-radius: 4px;
            border: none;
            cursor: pointer;
            background-color: #3498db;
            color: #fff;
            width: 100%;
        }
        img {
            border-radius: 0.5rem;
        }
    </style>
</head>
<body>
    {% include 'base/tab_login.html' %}
    {% include 'base/site_header.html' %}
    <div class="main-container">
        <div class="container">
            <form action="/updatefood/{{food.id}}/" method="post" enctype="multipart/form-data" class="form-data">
                {%csrf_token%}
                <div class="form-detail">
            
                    <div class="form_data">
                        <div class="food_name">
                            <label for="id_name">name</label>
                            <input type="text" name="name" step="any" required id="id_name" value="{{form.instance.name}}">
                        </div>
                        <div class="food_price">
                            <label for="id_price">price</label>
                            <input type="number" name="price" step="any" required id="id_price" value="{{form.instance.price}}">
                        </div>
                        <div class="food_unit">
                            <label for="id_unit">หน่วยต่อถุง</label>
                            <input type="text" name="unit" step="any" required id="id_unit" value="{{form.instance.unit}}">
                        </div>
                    </div>

                </div>
                
                <div class="form_image">
                    <div class="upload_image">
                        <label for="id_image"></label>
                        <!-- <img src="{{form.instance.image.url}}" alt="food-image"> -->
                        <!-- <input type="text" name="image_url" id="id_image" value="{{form.instance.image.url}}"> -->
                        <input type="file" name="image">
                    </div>
                </div>
                <input type="submit" value="submit">
                
            </form>
            
        </div>
        <div class="container-image">
            <div class="image-area">
                <img src="{{form.instance.image.url}}" alt="food-image">
            </div>
        </div>
        
    </div>
</body>
</html>